### ISSUE TITLE
Clarify behavior for concurrent writes

### ISSUE THREAD

**Issue by acoburn** [fcrepo/fcrepo-specification-atomic-operations#3]
It is currently unclear what correct behavior is for batch operations in which writes to the same resource are interleaved. This can occur in both a single-node and a distributed context, as well as in a synchronous or asynchronous environment.

This can be especially ambiguous for non-idempotent operations, such as PATCH:

```
Interleaving of multiple (PATCH) non-idempotent operations

TIME        Resource        Operation       Session     Comment
15:00:00    /foo            POST            (none)      /foo is created as an empty RDF resource
15:00:01    /foo            PATCH            1          INSERT { <> dc:title "one" } WHERE {}
15:00:02    /foo            PATCH            2          INSERT { <> dc:title "two" } WHERE {}
15:00:03                    (commit)         2          `<> dc:title "two"` is added to /foo
15:00:04                    (commit)         1          conflict? or overwrite? or append?
```

But ambiguities can also arise in the context of idempotent operations:

Interleaving of idempotent (PUT+DELETE) operations

```
TIME        Resource        Operation       Session     Comment
15:00:00    /foo            POST            (none)      /foo is created as an empty container
15:00:01    /foo/1          PUT             1           /foo/1 is created in session 1
15:00:02    /foo            DELETE          2           /foo is deleted in session 2
15:00:03    /foo/2          PUT             1           /foo/2 is created in session 1
15:00:04                    (commit)        2           /foo is deleted
15:00:05                    (commit)        1           conflict? or PUT-uncontained?
```

In both cases, the question arises about how to correctly apply the operations to the given resource.

**Comment by ajs6f** [comment]
Is it clear that a merge is the appropriate behavior at all here?

**Comment by acoburn** [comment]
Call it whatever you'd like. The question is how to handle the interleaving of operations.

**Comment by ajs6f** [comment]
Merging is radically different than failing an operation from the server side. In one case the expectation is that all requests succeed, in the other it is not. If you don't really demand that all requests succeed, please change the issue name.
